networks:
  sdcc_network:
    driver: bridge
    name: sdcc_network

services:
  discovery :
    image : python
    tty : true
    networks:
      - sdcc_network

  authentication :
    image : python
    tty : true
    networks:
      - sdcc_network

  edge :
    image : python
    tty : true
    networks:
      - sdcc_network
    volumes:
      - type : tmpfs
        target : /temp_storage
        tmpfs:
          size : 100M   ## Va per pagine di memoria principale (4k)
      - ./edge_src:/src

  rabbit_mq :
    image : rabbitmq
    tty : true
    networks :
      - sdcc_network
    
