# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login/Login.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11login/Login.proto\x12\x05login\";\n\x08UserInfo\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06passwd\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"b\n\x08Response\x12.\n\x08response\x18\x01 \x01(\x0e\x32\x1c.login.Response.ResponseType\"&\n\x0cResponseType\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x32\x39\n\x0cLoginService\x12)\n\x05login\x12\x0f.login.UserInfo\x1a\x0f.login.ResponseB\nZ\x08../protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login.Login_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010../proto'
  _globals['_USERINFO']._serialized_start=28
  _globals['_USERINFO']._serialized_end=87
  _globals['_RESPONSE']._serialized_start=89
  _globals['_RESPONSE']._serialized_end=187
  _globals['_RESPONSE_RESPONSETYPE']._serialized_start=149
  _globals['_RESPONSE_RESPONSETYPE']._serialized_end=187
  _globals['_LOGINSERVICE']._serialized_start=189
  _globals['_LOGINSERVICE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
