// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: EdgeFileTransfer.proto

package edge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCodes int32

const (
	ErrorCodes_OK                   ErrorCodes = 0
	ErrorCodes_CHUNK_ERROR          ErrorCodes = 10
	ErrorCodes_INVALID_TICKET       ErrorCodes = 11
	ErrorCodes_FILE_CREATE_ERROR    ErrorCodes = 12
	ErrorCodes_FILE_NOT_FOUND_ERROR ErrorCodes = 13
	ErrorCodes_FILE_WRITE_ERROR     ErrorCodes = 15
	ErrorCodes_FILE_READ_ERROR      ErrorCodes = 16
	ErrorCodes_STREAM_CLOSE_ERROR   ErrorCodes = 17
)

// Enum value maps for ErrorCodes.
var (
	ErrorCodes_name = map[int32]string{
		0:  "OK",
		10: "CHUNK_ERROR",
		11: "INVALID_TICKET",
		12: "FILE_CREATE_ERROR",
		13: "FILE_NOT_FOUND_ERROR",
		15: "FILE_WRITE_ERROR",
		16: "FILE_READ_ERROR",
		17: "STREAM_CLOSE_ERROR",
	}
	ErrorCodes_value = map[string]int32{
		"OK":                   0,
		"CHUNK_ERROR":          10,
		"INVALID_TICKET":       11,
		"FILE_CREATE_ERROR":    12,
		"FILE_NOT_FOUND_ERROR": 13,
		"FILE_WRITE_ERROR":     15,
		"FILE_READ_ERROR":      16,
		"STREAM_CLOSE_ERROR":   17,
	}
)

func (x ErrorCodes) Enum() *ErrorCodes {
	p := new(ErrorCodes)
	*p = x
	return p
}

func (x ErrorCodes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCodes) Descriptor() protoreflect.EnumDescriptor {
	return file_EdgeFileTransfer_proto_enumTypes[0].Descriptor()
}

func (ErrorCodes) Type() protoreflect.EnumType {
	return &file_EdgeFileTransfer_proto_enumTypes[0]
}

func (x ErrorCodes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCodes.Descriptor instead.
func (ErrorCodes) EnumDescriptor() ([]byte, []int) {
	return file_EdgeFileTransfer_proto_rawDescGZIP(), []int{0}
}

type EdgeFileDownloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *EdgeFileDownloadRequest) Reset() {
	*x = EdgeFileDownloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_EdgeFileTransfer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EdgeFileDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeFileDownloadRequest) ProtoMessage() {}

func (x *EdgeFileDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_EdgeFileTransfer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeFileDownloadRequest.ProtoReflect.Descriptor instead.
func (*EdgeFileDownloadRequest) Descriptor() ([]byte, []int) {
	return file_EdgeFileTransfer_proto_rawDescGZIP(), []int{0}
}

func (x *EdgeFileDownloadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type EdgeFileChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *EdgeFileChunk) Reset() {
	*x = EdgeFileChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_EdgeFileTransfer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EdgeFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeFileChunk) ProtoMessage() {}

func (x *EdgeFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_EdgeFileTransfer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeFileChunk.ProtoReflect.Descriptor instead.
func (*EdgeFileChunk) Descriptor() ([]byte, []int) {
	return file_EdgeFileTransfer_proto_rawDescGZIP(), []int{1}
}

func (x *EdgeFileChunk) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_EdgeFileTransfer_proto protoreflect.FileDescriptor

var file_EdgeFileTransfer_proto_rawDesc = []byte{
	0x0a, 0x16, 0x45, 0x64, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x65, 0x64, 0x67, 0x65, 0x22, 0x36,
	0x0a, 0x17, 0x45, 0x64, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x0d, 0x45, 0x64, 0x67, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x2a, 0xad, 0x01,
	0x0a, 0x0a, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x06, 0x0a, 0x02,
	0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x48, 0x55, 0x4e, 0x4b, 0x5f, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x0a, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44,
	0x5f, 0x54, 0x49, 0x43, 0x4b, 0x45, 0x54, 0x10, 0x0b, 0x12, 0x15, 0x0a, 0x11, 0x46, 0x49, 0x4c,
	0x45, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x0c,
	0x12, 0x18, 0x0a, 0x14, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55,
	0x4e, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x0d, 0x12, 0x14, 0x0a, 0x10, 0x46, 0x49,
	0x4c, 0x45, 0x5f, 0x57, 0x52, 0x49, 0x54, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x0f,
	0x12, 0x13, 0x0a, 0x0f, 0x46, 0x49, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x5f, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x10, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f,
	0x43, 0x4c, 0x4f, 0x53, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x11, 0x32, 0x5b, 0x0a,
	0x0f, 0x45, 0x64, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x48, 0x0a, 0x10, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x72, 0x6f, 0x6d,
	0x45, 0x64, 0x67, 0x65, 0x12, 0x1d, 0x2e, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x45, 0x64, 0x67, 0x65,
	0x46, 0x69, 0x6c, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x46,
	0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x64, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_EdgeFileTransfer_proto_rawDescOnce sync.Once
	file_EdgeFileTransfer_proto_rawDescData = file_EdgeFileTransfer_proto_rawDesc
)

func file_EdgeFileTransfer_proto_rawDescGZIP() []byte {
	file_EdgeFileTransfer_proto_rawDescOnce.Do(func() {
		file_EdgeFileTransfer_proto_rawDescData = protoimpl.X.CompressGZIP(file_EdgeFileTransfer_proto_rawDescData)
	})
	return file_EdgeFileTransfer_proto_rawDescData
}

var file_EdgeFileTransfer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_EdgeFileTransfer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_EdgeFileTransfer_proto_goTypes = []interface{}{
	(ErrorCodes)(0),                 // 0: edge.ErrorCodes
	(*EdgeFileDownloadRequest)(nil), // 1: edge.EdgeFileDownloadRequest
	(*EdgeFileChunk)(nil),           // 2: edge.EdgeFileChunk
}
var file_EdgeFileTransfer_proto_depIdxs = []int32{
	1, // 0: edge.EdgeFileService.DownloadFromEdge:input_type -> edge.EdgeFileDownloadRequest
	2, // 1: edge.EdgeFileService.DownloadFromEdge:output_type -> edge.EdgeFileChunk
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_EdgeFileTransfer_proto_init() }
func file_EdgeFileTransfer_proto_init() {
	if File_EdgeFileTransfer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_EdgeFileTransfer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EdgeFileDownloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_EdgeFileTransfer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EdgeFileChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_EdgeFileTransfer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_EdgeFileTransfer_proto_goTypes,
		DependencyIndexes: file_EdgeFileTransfer_proto_depIdxs,
		EnumInfos:         file_EdgeFileTransfer_proto_enumTypes,
		MessageInfos:      file_EdgeFileTransfer_proto_msgTypes,
	}.Build()
	File_EdgeFileTransfer_proto = out.File
	file_EdgeFileTransfer_proto_rawDesc = nil
	file_EdgeFileTransfer_proto_goTypes = nil
	file_EdgeFileTransfer_proto_depIdxs = nil
}
