// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: LoadBalancer.proto

package load_balancer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCodesLoadBalancer int32

const (
	ErrorCodesLoadBalancer_OK                  ErrorCodesLoadBalancer = 0
	ErrorCodesLoadBalancer_NO_SERVER_AVAILABLE ErrorCodesLoadBalancer = 20
)

// Enum value maps for ErrorCodesLoadBalancer.
var (
	ErrorCodesLoadBalancer_name = map[int32]string{
		0:  "OK",
		20: "NO_SERVER_AVAILABLE",
	}
	ErrorCodesLoadBalancer_value = map[string]int32{
		"OK":                  0,
		"NO_SERVER_AVAILABLE": 20,
	}
)

func (x ErrorCodesLoadBalancer) Enum() *ErrorCodesLoadBalancer {
	p := new(ErrorCodesLoadBalancer)
	*p = x
	return p
}

func (x ErrorCodesLoadBalancer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCodesLoadBalancer) Descriptor() protoreflect.EnumDescriptor {
	return file_LoadBalancer_proto_enumTypes[0].Descriptor()
}

func (ErrorCodesLoadBalancer) Type() protoreflect.EnumType {
	return &file_LoadBalancer_proto_enumTypes[0]
}

func (x ErrorCodesLoadBalancer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCodesLoadBalancer.Descriptor instead.
func (ErrorCodesLoadBalancer) EnumDescriptor() ([]byte, []int) {
	return file_LoadBalancer_proto_rawDescGZIP(), []int{0}
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logged bool `protobuf:"varint,1,opt,name=logged,proto3" json:"logged,omitempty"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LoadBalancer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LoadBalancer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_LoadBalancer_proto_rawDescGZIP(), []int{0}
}

func (x *LoginResponse) GetLogged() bool {
	if x != nil {
		return x.Logged
	}
	return false
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Passwd   string `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LoadBalancer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_LoadBalancer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_LoadBalancer_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPasswd() string {
	if x != nil {
		return x.Passwd
	}
	return ""
}

type BalancerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EdgeIpAddr string `protobuf:"bytes,1,opt,name=edgeIpAddr,proto3" json:"edgeIpAddr,omitempty"`
	RequestId  string `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
}

func (x *BalancerResponse) Reset() {
	*x = BalancerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_LoadBalancer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalancerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalancerResponse) ProtoMessage() {}

func (x *BalancerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_LoadBalancer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalancerResponse.ProtoReflect.Descriptor instead.
func (*BalancerResponse) Descriptor() ([]byte, []int) {
	return file_LoadBalancer_proto_rawDescGZIP(), []int{2}
}

func (x *BalancerResponse) GetEdgeIpAddr() string {
	if x != nil {
		return x.EdgeIpAddr
	}
	return ""
}

func (x *BalancerResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_LoadBalancer_proto protoreflect.FileDescriptor

var file_LoadBalancer_proto_rawDesc = []byte{
	0x0a, 0x12, 0x4c, 0x6f, 0x61, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x72, 0x22, 0x27, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x64, 0x22, 0x3a, 0x0a, 0x04,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x22, 0x50, 0x0a, 0x10, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x65, 0x64, 0x67, 0x65, 0x49, 0x70, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x65, 0x64, 0x67, 0x65, 0x49, 0x70, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1c, 0x0a, 0x09,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x2a, 0x39, 0x0a, 0x16, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x4c, 0x6f, 0x61, 0x64, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x72, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13,
	0x4e, 0x4f, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41,
	0x42, 0x4c, 0x45, 0x10, 0x14, 0x32, 0x95, 0x01, 0x0a, 0x10, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x45, 0x64, 0x67, 0x65, 0x12, 0x13, 0x2e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x62, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x1f, 0x2e, 0x6c, 0x6f, 0x61,
	0x64, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x13, 0x2e, 0x6c, 0x6f, 0x61,
	0x64, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x1a,
	0x1c, 0x2e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x18, 0x5a,
	0x16, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_LoadBalancer_proto_rawDescOnce sync.Once
	file_LoadBalancer_proto_rawDescData = file_LoadBalancer_proto_rawDesc
)

func file_LoadBalancer_proto_rawDescGZIP() []byte {
	file_LoadBalancer_proto_rawDescOnce.Do(func() {
		file_LoadBalancer_proto_rawDescData = protoimpl.X.CompressGZIP(file_LoadBalancer_proto_rawDescData)
	})
	return file_LoadBalancer_proto_rawDescData
}

var file_LoadBalancer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_LoadBalancer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_LoadBalancer_proto_goTypes = []interface{}{
	(ErrorCodesLoadBalancer)(0), // 0: load_balancer.ErrorCodesLoadBalancer
	(*LoginResponse)(nil),       // 1: load_balancer.LoginResponse
	(*User)(nil),                // 2: load_balancer.User
	(*BalancerResponse)(nil),    // 3: load_balancer.BalancerResponse
}
var file_LoadBalancer_proto_depIdxs = []int32{
	2, // 0: load_balancer.BalancingService.GetEdge:input_type -> load_balancer.User
	2, // 1: load_balancer.BalancingService.LoginClient:input_type -> load_balancer.User
	3, // 2: load_balancer.BalancingService.GetEdge:output_type -> load_balancer.BalancerResponse
	1, // 3: load_balancer.BalancingService.LoginClient:output_type -> load_balancer.LoginResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_LoadBalancer_proto_init() }
func file_LoadBalancer_proto_init() {
	if File_LoadBalancer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_LoadBalancer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LoadBalancer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_LoadBalancer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalancerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_LoadBalancer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_LoadBalancer_proto_goTypes,
		DependencyIndexes: file_LoadBalancer_proto_depIdxs,
		EnumInfos:         file_LoadBalancer_proto_enumTypes,
		MessageInfos:      file_LoadBalancer_proto_msgTypes,
	}.Build()
	File_LoadBalancer_proto = out.File
	file_LoadBalancer_proto_rawDesc = nil
	file_LoadBalancer_proto_goTypes = nil
	file_LoadBalancer_proto_depIdxs = nil
}
