# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from file_transfer import EdgeFileTransfer_pb2 as file__transfer_dot_EdgeFileTransfer__pb2


class EdgeFileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DownloadFromEdge = channel.unary_stream(
                '/edge.EdgeFileService/DownloadFromEdge',
                request_serializer=file__transfer_dot_EdgeFileTransfer__pb2.EdgeFileDownloadRequest.SerializeToString,
                response_deserializer=file__transfer_dot_EdgeFileTransfer__pb2.EdgeFileChunk.FromString,
                )


class EdgeFileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DownloadFromEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdgeFileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DownloadFromEdge': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFromEdge,
                    request_deserializer=file__transfer_dot_EdgeFileTransfer__pb2.EdgeFileDownloadRequest.FromString,
                    response_serializer=file__transfer_dot_EdgeFileTransfer__pb2.EdgeFileChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edge.EdgeFileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EdgeFileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DownloadFromEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/edge.EdgeFileService/DownloadFromEdge',
            file__transfer_dot_EdgeFileTransfer__pb2.EdgeFileDownloadRequest.SerializeToString,
            file__transfer_dot_EdgeFileTransfer__pb2.EdgeFileChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
